### ISSUE TITLE
unrecognized import path "math/bits"

### ISSUE THREAD

**Issue by rkablukov** [ValidatorCenter/AutodelegateTool#8]
Загружаю SDK и получаю ошибки (см. ниже). Версия golang 1.6.2. Платформа Ubuntu 18.04

```
$ go get -u "github.com/ValidatorCenter/minter-go-sdk"
package math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)
package context: unrecognized import path "context" (import path does not begin with hostname)
```

**Comment by dkodnik** [comment]
Вам нужно обновить версию Go. Пакет "math/bits" был добавлен в golang с версии 1.9.

https://golang.org/doc/go1.9#math-bits

**Comment by rkablukov** [comment]
Да, спасибо!

If you're using Ubuntu 16.04 LTS, 18.04 LTS or 18.10, then you can use the longsleep/golang-backports PPA and install Go 1.11.

sudo add-apt-repository ppa:longsleep/golang-backports
sudo apt-get update
sudo apt-get install golang-go
